---
npm:
  platforms:
    - name: linux
      os: ubuntu
      architecture: x86_64
    - name: linux
      os: ubuntu
      architecture: x86
    - name: darwin
      os: macos
      architecture: x86_64
    - name: windows
      os: windows
      architecture: x86_64
    - name: windows
      os: windows
      architecture: x86
